apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogs
  labels:
    app: catalogs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalogs
  template:
    metadata:
      labels:
        app: catalogs
    spec:
      containers:
        - name: catalogs
          image: go-catalogs:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: catalogs
spec:
  selector:
    app: catalogs
  type: NodePort
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
