name: CI to Docker Hub
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Check Out Repo 
          uses: actions/checkout@v2
        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v1
        - name: Extract tag name
          id: tag
          run: |
            echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
            echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
            echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
        - name: Build and push
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            context: ./
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/go-catalogs:${{ steps.tag.outputs.SOURCE_TAG }}
        - name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}
