name: CI to Docker Hub
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Check Out Repo 
          uses: actions/checkout@v2
        - name: Login to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_HUB_USERNAME }}
            password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v1
        - name: Extract tag name
          id: tag
          uses: actions/github-script@0.2.0
          with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
              return context.payload.ref.replace(/\/refs\/tags\//, '');
        - name: Build and push
          id: docker_build
          uses: docker/build-push-action@v2
          with:
            context: ./
            file: ./Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_HUB_USERNAME }}/go-catalogs:${{ steps.tag.outputs.result }}
        - name: Image digest
          run: echo ${{ steps.docker_build.outputs.digest }}
